name: Publish to Nexus

on:
  push:
    branches:
      - main       # or the branch you want to trigger publishing on
  workflow_dispatch: # allows manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK (Gradle Kotlin JVM target)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Step 4: Set Nexus credentials from GitHub Secrets
      - name: Configure Nexus credentials
        run: |
          echo "nexusUsername=${{ secrets.NEXUS_USERNAME }}" >> $GITHUB_ENV
          echo "nexusPassword=${{ secrets.NEXUS_PASSWORD }}" >> $GITHUB_ENV

      # Step 5: Run Gradle publish
      - name: Publish to Nexus
        run: ./gradlew publish --no-configuration-cache
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
